### ISSUE TITLE
buildessential's dependency list needs changes 

### ISSUE THREAD

**Issue by perryh2** [skycocker/chromebrew#3207] opened 2019-03-03 08:23 UTC
When install.sh starts to install buildessential, the reported dependency list is not entirely correct.  gcc8 has already been installed, so gcc7 should not be needed; and bz2, xzutils, sed, attr, and bc (and possibly some others) are already included in Chrome OS itself.

## Versions and system information
chromebrew: 1.2.1

ChromeOS: 
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BB86912A-29BE-A59B-31EF-8F4DD1C023E2}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BB86912A-29BE-A59B-31EF-8F4DD1C023E2}
CHROMEOS_RELEASE_BOARD=enguarde-signed-mp-v25keys
CHROMEOS_RELEASE_BRANCH_NUMBER=113
CHROMEOS_RELEASE_BUILDER_PATH=enguarde-release/R71-11151.113.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.113.0 (Official Build) stable-channel enguarde 
CHROMEOS_RELEASE_KEYSET=mp-v25
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.113.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.113.0

Model: Lenovo N21 Chromebook

Architecture: x86_64

**Comment by JL2210** [comment] 2019-03-03 13:22
Is this a fresh reinstall?

**Comment by JL2210** [comment] 2019-03-03 13:23
If you add the '-S' flag while installing, `gcc7` is pulled in because
already installed packages are not skipped. Lovely, isn't it?

**Comment by JL2210** [comment] 2019-03-03 21:34
> bz2, xzutils, sed, attr, and bc (and possibly some others) are already included in Chrome OS itself.

bz2: We need `libbzip2`, the bzip2 decompression library

xzutils: We need `liblzma`, the lzma decompression library

sed: Has some major issues involving Chrome/Chromium forcing a non-optimal decision (blocking `e/r/w` commands) upon its users. Also needed updated.

attr: Needed header files and an update.

bc: Needed an update.

**Comment by uberhacker** [comment] 2019-03-08 18:27
Should we mention #3187 as the root cause of this issue?  If so, I'm thinking we should close this and continue the conversation on that issue instead?

**Comment by JL2210** [comment] 2019-03-25 16:36
@uberhacker Can you remove the [x86_64] tag? Not relevant.

**Comment by uberhacker** [comment] 2019-03-25 20:59
His architecture is x86_64 so it is relevant.  But since this issue is stale with no feedback, I will close.

**Closed by uberhacker** 2019-03-25 20:59 UTC
Labels: bug, x86_64

**Comment by JL2210** [comment] 2019-03-25 21:18
Yes, but there's literally no correlation between buildessential's dependency list and x86_64, so why have the tag?

**Comment by uberhacker** [comment] 2019-03-25 21:23
Did you see the architecture that was reported in the first comment?
