### ISSUE TITLE
Broken symlink in isl 0.20 package

### ISSUE THREAD

**Issue by jonathonmcmurray** [skycocker/chromebrew#2588] opened 2018-08-22 16:24 UTC
## Description
After installing isl 0.20 package, there is a broken symlink named `libisl.so.15` pointing to `libisl.so.20` which doesn't exist. (Seems like this file _should_ exist based on package version)

If you executed a specific command:
```shell
chronos@localhost ~/Downloads $ ls -lFh /usr/local/lib64/libisl.*
```

Output:
```shell
-rw-r--r--. 1 chronos chronos 4.2M Aug 22 16:11 /usr/local/lib64/libisl.a
-rwxr-xr-x. 1 chronos chronos  938 Aug 12 22:01 /usr/local/lib64/libisl.la*
lrwxrwxrwx. 1 chronos chronos   16 Aug 12 22:01 /usr/local/lib64/libisl.so -> libisl.so.19.1.0*
lrwxrwxrwx. 1 chronos chronos   29 Aug 12 22:01 /usr/local/lib64/libisl.so.15 -> /usr/local/lib64/libisl.so.20
lrwxrwxrwx. 1 chronos chronos   16 Aug 12 22:01 /usr/local/lib64/libisl.so.19 -> libisl.so.19.1.0*
-rwxr-xr-x. 1 chronos chronos 2.3M Aug 22 16:11 /usr/local/lib64/libisl.so.19.1.0*
```

## Versions and system information
chromebrew: `crew --version`

`1.0.3`

ChromeOS: `cat /etc/lsb-release`

```
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4856647
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={196C49C7-152F-499B-9C64-F5B8A89E43A4}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={196C49C7-152F-499B-9C64-F5B8A89E43A4}
CHROMEOS_RELEASE_BOARD=edgar-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=edgar-release/R67-10575.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=10575
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=67
CHROMEOS_RELEASE_DESCRIPTION=10575.58.0 (Official Build) stable-channel edgar
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10575.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10575.58.0
```

Model: Acer Chromebook 14

Architecture: `uname -m`

`x86_64`

## Addtional information

What I think needs to be done:
- [ ] include correct `.so` file version
- [ ] update all symlinks to valid location

**Comment by superloach** [comment] 2018-08-22 18:36
That's weird, guess they didn't *actually* update the binaries?

**Comment by uberhacker** [comment] 2018-08-22 18:39
Closing since this is a duplicate of issue: https://github.com/skycocker/chromebrew/issues/2567

**Closed by uberhacker** 2018-08-22 18:39 UTC
