### ISSUE TITLE
Bash error "Segmentation fault (core dumped)" results after compiling with gcc

### ISSUE THREAD

**Issue by bmorris22** [skycocker/chromebrew#198] opened 2016-07-11 02:56 UTC
What I was doing: Compiling (using the gcc toolchain provided by chromebrew) and installing a small library using the standard 
`./configure
make
sudo make install`

What happened: No errors were reported from make or gcc during this process In fact it installed correctly on my machine. Now when I call bash I get 
`/bin/bash: symbol lookup error: /bin/bash: undefined symbol: rl_signal_event_hook`
if I try calling programs from /usr/local/bin (nano, gcc,ruby, crew, etc.) I'm greeted with
`Segmentation fault (core dumped)'
 
What I tried: Restarting the machine

Any ideas?

**Comment by lyxell** [comment] 2016-07-11 05:52
Duplicate of #190?

**Closed** 2016-07-12 01:57 UTC
