### ISSUE TITLE
make build fails

### ISSUE THREAD

**Issue by dantrevino** [skycocker/chromebrew#797] opened 2017-06-25 06:04 UTC
chronos@localhost / $ crew install make keep
...
./config.status: line 3183: cmp: command not found
pkgconfig failed to install: `make -j4` exited with 127

**Comment by jam7** [comment] 2017-06-25 06:37
It is caused by a difficult to solve dependency problem.  :(

You can avoid this problem by `crew install buildessential`.

**Comment by jam7** [comment] 2017-07-04 11:20
This issue will be fixed once #815 is merged.

**Comment by jam7** [comment] 2017-07-31 09:15
Close in favor of #815.

**Closed by jam7** 2017-07-31 09:15 UTC
