### ISSUE TITLE
Nano displays weirdly

### ISSUE THREAD

**Issue by drbree82** [skycocker/chromebrew#161] opened 2016-04-22 01:00 UTC
Installed Nano on my Samsung Series 5 chromebook, installation went well.

When I ran nano, the terminal flickered, as if it was competing with the prompt for display time or something. I say this because the flicker was intermittently showing the uncleared command prompt, then back to nano.

Will probably just have to use vim instead, but if this gets fixed, that would be awesome.

**Comment by lyxell** [comment] 2016-04-22 11:48
I can't reproduce this, could you provide the log for the nano installation?

**Comment by drbree82** [comment] 2016-04-22 22:47
Wish I could, switched back to standard mode and wiped the logs. Stupid I know. I will try it when I have time(probably tonight)

If the log doesn't show any faults, I'll try getting a video for you.

**Comment by lyxell** [comment] 2016-04-23 18:00
Even if the logs doesn't show any faults they could be useful.

**Comment by lyxell** [comment] 2016-12-13 22:42
Closing as unreproducible. Feel free to reopen.

**Closed by lyxell** 2016-12-13 22:42 UTC

**Comment by MD5HashBrowns** [comment] 2017-07-07 18:33
@drbree82 I know this is old, but I was having this same problem and noticed, as a workaround, that running nano within a `screen` session works fine.

**Comment by lyxell** [comment] 2017-07-08 03:21
@MD5HashBrowns This makes me think this is an issue with the TERM environment variable, try fiddling around with it, e.g. setting `export TERM=screen` outside of screen and see if it helps.

**Comment by MD5HashBrowns** [comment] 2017-07-08 03:40
@lyxell Changing the TERM env variable didn't seem to make an difference. Also, this issue does not appear when running nano from the Developer Console (by using CTRL-ALT-F2) which has the same TERM env variable set.
