### ISSUE TITLE
Problem with FydeOS 10 (curl stop working during installation)

### ISSUE THREAD

**Issue by iz0eyj** [skycocker/chromebrew#4347] opened 2020-09-29 18:12 UTC
## Description
Provide a short description of your problem here.
The installation of Chromebrew creates problems already on the installation of "libressl".
There appear to be incompatibilities that make the curl command unusable.

```
chronos@localhost ~/Downloads $ curl -Ls git.io/vddgY | bash
Creating new device.json...
Downloading gcc8...
######################################################################## 100.0%
Verifying gcc8...
gcc8-8.3.0-chromeos-x86_64.tar.xz: OK
Extracting gcc8 (this may take a while)...
Installing gcc8 (this may take a while)...
Adding new information on gcc8 to device.json...
Downloading libressl...
######################################################################## 100.0%
Verifying libressl...
libressl-3.0.2-2-chromeos-x86_64.tar.xz: OK
Extracting libressl (this may take a while)...
Installing libressl (this may take a while)...
Adding new information on libressl to device.json...
Downloading ruby...
curl: symbol lookup error: /usr/lib64/libcurl.so.4: undefined symbol: SSL_COMP_free_compression_methods

```

I can't find a way to get curl back to working.

FydeOS 10.2 running on Asus LiveBook Pro (Core i7, 16 GB RAM)

Thanks, Federico
---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment] 2020-09-29 18:21
@iz0eyj: We currently don't support FydeOS but I imagine if you can figure out a way to install the Chromebrew version curl before ruby, that may solve your issue.  That said, the challenge will be to not only install curl but it's dependencies as well.  The file you would need to edit is install.sh.

**Comment by iz0eyj** [comment] 2020-09-29 18:57
Thanks @uberhacker 

looking at progression the problem would appear in libressl (unsupported version?).
Chromebrew worked flawlessly with FydeOS versions 9.x and stopped running after updating at 10.x.
I have been using fydeOD for a very long time and this is the first difference I find with ChromeOS.

Do you think it is possible and / or appropriate to fork Chromebrew and make a version for FydeOS?

**Comment by uberhacker** [comment] 2020-09-29 19:07
The ideal situation would be to have a universal install that works for all Chrom(e/ium)OS variants.  That said, it would be difficult to support all of them since these fork projects have idosyncrasies that present different challenges.

**Comment by ThatGeekyWeeb** [comment] 2020-09-29 19:29
The fix for this issue is compiling a custom version of curl, and using it to replace the original one. The custom compilation needs  to be set to use some kind of `tls` implementation, such as `gnutls` or `mbedtls`, and should be statically compiled to revent issues when libraries are replaced

**Comment by iz0eyj** [comment] 2020-09-29 19:37
@uberhacker Hi

I also don't like forks, unless they are absolutely essential.
However FydeOS is gaining ground both among the common user and among us developers because it allows you to have a powerful machine and virtually indistinguishable from the "real" Chromebook even in areas of the world where the original Core i7 class machines are not imported (for example example our Italy).

Can I ask you if that step from which the problems begin is essential or if it can be replaced with software components already present in ChromeOS / FydeOS?

However, if I can be useful as a debugger to get a unified version then you have me too.

Thank you

@ThatGeekyWeeb 
Hi Mia, but I would also prefer a unified version.

**Comment by uberhacker** [comment] 2020-09-29 19:42
In order to look into it, I would need to install FydeOS myself and see how well it works.  I have an old laptop that I could test on when I get some more time.  Definitely an interesting challenge.

**Comment by iz0eyj** [comment] 2020-09-29 19:53
Unlikely to work on an old machine, FydeOS only supports relatively recent machines with Intel graphics well.
If the topic interests you, a few months ago I wrote some articles with increasing degrees of depth on our blog (uncino.eu).
I'm in Italian but Google translates well :)

Now I'm working on some software for the ESP32s (do you know them?) And it would be more practical for me to use Crew rather than the usual Crouton ... I went to install what I needed and ... I found that it no longer worked: )

**Comment by ThatGeekyWeeb** [comment] 2020-09-29 21:59
Honestly, I feel the old issue I opened about installing non-`openssl` curl, before `libressl` would be the best fit for this, and it should help support alot more devices.
See: #4292

**Comment by iz0eyj** [comment] 2020-09-30 15:14
Hi @ThatGeekyWeeb 
I need to find some time to start from scratch with FydeOS and reload the entire development environment from Cloud backups. There seems to be no way to restart curl and experiment.
I also tried to make a dd of the third partition from an original pendrive, but nothing.

Do you use FydeOS too?

**Comment by iz0eyj** [comment] 2020-09-30 15:45
Hey @uberhacker & @ThatGeekyWeeb the suggested 

`export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib`

worked for me, now I can use Crew again!

```
chronos@localhost / $ curl --version
curl 7.68.0 (x86_64-cros-linux-gnu) libcurl/7.68.0 OpenSSL/1.0.2u zlib/1.2.11
Release-Date: 2020-01-08
Protocols: dict file ftp ftps http https 
Features: HTTPS-proxy IPv6 Largefile libz NTLM SSL TLS-SRP UnixSockets
chronos@localhost / $ 
```
I think it is the original curl

Example:

```
chronos@localhost / $ crew install gnucobol
gnucobol: GnuCOBOL (formerly OpenCOBOL) is a free COBOL compiler.
https://open-cobol.sourceforge.io/
version 3.0-rc1
The following packages also need to be installed: 
libdb 
Do you agree? [Y/n] y
Proceeding...
libdb: Berkeley DB is a family of embedded key-value database libraries providing scalable high-performance data management services to applications.
http://www.oracle.com/technetwork/database/database-technologies/berkeleydb/overview/index.html
version 6.2.32
Precompiled binary available, downloading...
############################################################################################################################################################################################################## 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...
Precompiled binary available, downloading...
############################################################################################################################################################################################################## 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...
Gnucobol installed!
chronos@localhost / $ curl --version
curl 7.68.0 (x86_64-cros-linux-gnu) libcurl/7.68.0 OpenSSL/1.0.2u zlib/1.2.11
Release-Date: 2020-01-08
Protocols: dict file ftp ftps http https 
Features: HTTPS-proxy IPv6 Largefile libz NTLM SSL TLS-SRP UnixSockets
chronos@localhost / $ 

```
Thanks

**Comment by vincowl** [comment] 2020-09-30 18:35
@iz0eyj Since it looks like you have a x86_64 arch (cf `curl --version`), maybe you should also add `/usr/local/lib64` to your `LD_LIBRARY_PATH`

**Comment by ThatGeekyWeeb** [comment] 2020-09-30 19:20
@iz0eyj, No I don't use FydeOS, but I am using a very out of date ChromeOS, and `libressl` is only compatible with the latest version of ChromeOS. I've linked a package script for the custom version of curl I use, it should be issue-free! Simply install curl using `crew`, after copying the script to `/usr/local/lib64/crew/packages/`
> https://github.com/ThatGeekyWeeb/chromebrew/raw/openssl-repack/packages/curl.rb

**Comment by iz0eyj** [comment] 2020-09-30 21:25
@uberhacker 
Yes, sorry ... I wrote by heart and in a hurry; the complete export is:

```
chronos@localhost / $ printenv LD_LIBRARY_PATH
/lib64:/usr/lib64:/usr/local/lib64
chronos@localhost / $ 

```
Now I'm trying to get sommelier to work, available in the repository packages, and I think I'm well under way.

@ThatGeekyWeeb 
hanks Mia, but apparently my machine runs Chromebrew well with its original curl.
To be honest, it is not clear to me why we need to install a curl other than the one already available with ChromeOS ...
I'm thinking about forking myself to have more flexibility.

If you have a very old Chromebook why not do a test to determine if maybe you have a newer machine compatible with FydeOS?

**Comment by ThatGeekyWeeb** [comment] 2020-10-01 00:10
> To be honest, it is not clear to me why we need to install a curl other than the one already available with ChromeOS ...

@iz0eyj ChromeOS's curl is dynamically linked, when you install Chromebrew, it changes the path to these libraries, and then installs `libressl`, most likely these libraries won't be compatible with the current version of curl, the only way to fix this is to compile curl fresh with this version of `libressl` or to custom compile curl to not use `libressl` at all.

**Comment by satmandu** [comment] 2020-10-05 13:54
Would adding a ```depends_on 'libressl'``` to the curl script fix this?

**Comment by ThatGeekyWeeb** [comment] 2020-10-05 13:58
no, `libressl` is installed as a core package for Chromebrew, and therefore is installed regardless. The issue is due to the fact that you can just swap libraries, ChromeOS uses openssl, which is vastly different from libressl, the dynamic links don't match, and various old, and deprecated symbols are missing.

**Comment by ThatGeekyWeeb** [comment] 2020-10-05 14:06
This works fine on ChromeOS 85/84, but on older outdated versions, curl has to be recompiled, I can guarantee that FydeOS 10 is based on an old version of ChromeOS, with a very outdated set of openssl libraries.

**Comment by satmandu** [comment] 2020-10-05 15:33
@ThatGeekyWeeb Would it make sense to have a static curl for just those machines with older openssl installs?

**Comment by satmandu** [comment] 2020-10-05 15:35
(Also maybe the primary script could just check to see if curl returns an error and if so just use the builtin curl for everything?)

**Comment by ThatGeekyWeeb** [comment] 2020-10-05 17:56
We can't just use the builtin curl, ruby requires some kind of SSL implementation to exist, I was able to fake such using some symlinks, but it ends badly for anything trying to find a real SSL implementation, the only fix that has a 100% chance to work, is a static compilation of curl during original install.

**Closed** 2020-10-08 17:14 UTC
Labels: question, wontfix
