### ISSUE TITLE
Document / install step for partitions mounted noexec

### ISSUE THREAD

**Issue by dhasenan** [skycocker/chromebrew#136] opened 2016-01-13 05:17 UTC
Some versions of chromeos mount many partitions with the `noexec` flag. This means that, while gcc can create executables in those directories, configure scripts can't execute them. So the configure scripts fail, claiming that GCC can't produce executables. That kind of makes it hard to install software

If it were at least documented which directory is used for compiling things, I could remount that without the noexec flag manually.

Ideally this would be handled in the installation script.

**Comment by thedamian** [comment] 2016-01-13 21:45
Now I believe all compilation and installations happen in the tmp directories. which DO allow executable (that's why all current packages work)

Can you give us your example or where it failed you?

Also can you explain what you'd like chromebrew to do about this issue?

**Comment by skycocker** [comment] 2016-01-26 00:18
@dhasenan as @thedamian mentioned, chromebrew brew directories should allow file execution. If I understood you correctly - the request you are making is to make some kind of readme/wiki about that?

**Comment by dhasenan** [comment] 2016-01-26 01:05
Perhaps this isn't universally applied. I have been able to install some packages, but libsigsegv-2.10 claims that GCC can't create executables, and the simplest explanation would be that it's running configure on a partition that's marked noexec.

Is there a way to print the directory in which it's running configure?

**Comment by skycocker** [comment] 2016-01-26 11:04
@dhasenan this is probably a completely different problem than the noexec flag. Could you paste the whole sigsegv build output?

**Comment by dhasenan** [comment] 2016-01-26 15:55
```
Build Tools:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc -m64
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
libsigsegv failed to install: `./configure --libdir=/usr/local/lib64/ CC="gcc -m64" CFLAGS=" -fPIC"` exited with 77
```

It claims it's working in /usr/local/tmp/crew/libsigsegv-2.10, but I don't see any files that it creates there.

When I compile a hello world program and stick it on a partition that allows executing files, it works.

**Comment by thedamian** [comment] 2016-01-26 21:02
Google-ing "C compiler cannot create executables" doesn't reply much with permissions problems but with you either compiling with the wrong flages (64bit on a 32bit platforms)

OR (more likely) 

You missing the "crew install buildessential" and "crew install gcc" BEFORE you try to install what ever you're having trouble with.

Let us know if this works.

**Comment by dhasenan** [comment] 2016-01-27 06:44
The "more likely" didn't pan out:

```
chronos@localhost ~/Downloads $ sudo crew install buildessential gcc
Found buildessential, version 1.0
Following packages also need to be installed: 
binutils gmp mpc mpfr glibc gcc make linuxheaders 
Do you agree? [Y/n]

Proceeding...
Found binutils, version 2.23.2
Package binutils already installed, skipping...
Found gmp, version 5.1.2
Package gmp already installed, skipping...
Found mpc, version 1.0.1
Package mpc already installed, skipping...
Found mpfr, version 3.1.2
Package mpfr already installed, skipping...
Found glibc, version 2.17.90-baseline
Package glibc already installed, skipping...
Found gcc, version 4.8.1-baseline
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.4.0
Package linuxheaders already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
chronos@localhost ~/Downloads $ sudo crew install libsigsegv
Found libsigsegv, version 2.10
Found libsigsegv, version 2.10
No precompiled binary available for your platform, downloading source...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2016-01-26 22:43:17--  ftp://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.10.tar.gz
           => 'libsigsegv-2.10.tar.gz'
Resolving ftp.gnu.org... 208.118.235.20
Connecting to ftp.gnu.org|208.118.235.20|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /gnu/libsigsegv ... done.
==> SIZE libsigsegv-2.10.tar.gz ... 402279
==> PASV ... done.    ==> RETR libsigsegv-2.10.tar.gz ... done.
Length: 402279 (393K) (unauthoritative)

libsigsegv-2.10.tar.gz                100%[========================================================================>] 392.85K   675KB/s   in 0.6s   

2016-01-26 22:43:19 (675 KB/s) - 'libsigsegv-2.10.tar.gz' saved [402279]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...

Build Tools:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc -m64
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by thedamian** [comment] 2016-01-27 16:11
Indeed @dhasenan 

Can you try this line:

$ ln -s /usr/local/bin/gcc /usr/local/bin/cc

then run the "crew install buildessential gcc"

no need for sudo. (try without it first)

**Comment by dhasenan** [comment] 2016-01-27 18:13
No change. sudo was required (probably because I'd used it when first installing crew? -- guessing here)

**Comment by thedamian** [comment] 2016-01-27 18:40
When testing you have to be as verbose as possible. @dhasenan 

1) You tried the ln and then tried the same line as you did before. and no change.
2) you tried the ln and then you tried WITHOUT sudo and no change.
3) you tried the ln and nothing, and no change?

Help us with which one.

ALSO what platform are you on. 

And have you tried: "crew update" first (and then the lines above again)

step us through what you're seeing and what you've done.

**Comment by dhasenan** [comment] 2016-01-27 18:57
sudo seems to be required for all commands modifying /usr/local, which is owned by root and chmodded 755. I created a symlink from /usr/local/bin/cc to /usr/local/bin/gcc and it didn't help. After running crew update, the original error persisted.

Running on ChromeOS:
Version 49.0.2623.0 dev (64-bit)
Platform 7834.0.0 (Official Build) dev-channel parrot
Firmware Google_Parrot.2685.37.0

```
chronos@localhost ~/Downloads $ cd /usr/local/bin/
chronos@localhost /usr/local/bin $ ls -l gcc cc
ls: cannot access cc: No such file or directory
-rwxr-xr-x 3 chronos chronos 3107019 Oct  5  2013 gcc
chronos@localhost /usr/local/bin $ ln -s gcc cc
ln: failed to create symbolic link ‘cc’: Permission denied
chronos@localhost /usr/local/bin $ sudo ln -s gcc cc
chronos@localhost /usr/local/bin $ crew install libsigsegv
Found libsigsegv, version 2.10
Found libsigsegv, version 2.10
No precompiled binary available for your platform, downloading source...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

libsigsegv-2.10.tar.gz: Permission denied
rm: cannot remove ‘dest’: Permission denied
mkdir: cannot create directory ‘dest’: File exists
/usr/local/bin/crew:146:in `read': No such file or directory - ./libsigsegv-2.10.tar.gz (Errno::ENOENT)
        from /usr/local/bin/crew:146:in `block in download'
        from /usr/local/bin/crew:144:in `chdir'
        from /usr/local/bin/crew:144:in `download'
        from /usr/local/bin/crew:227:in `install'
        from /usr/local/bin/crew:159:in `resolveDependenciesAndInstall'
        from /usr/local/bin/crew:350:in `<main>'
chronos@localhost /usr/local/bin $ sudo crew install libsigsegv
Found libsigsegv, version 2.10
Found libsigsegv, version 2.10
No precompiled binary available for your platform, downloading source...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2016-01-27 10:12:12--  ftp://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.10.tar.gz
           => 'libsigsegv-2.10.tar.gz'
Resolving ftp.gnu.org... 208.118.235.20
Connecting to ftp.gnu.org|208.118.235.20|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /gnu/libsigsegv ... done.
==> SIZE libsigsegv-2.10.tar.gz ... 402279
==> PASV ... done.    ==> RETR libsigsegv-2.10.tar.gz ... done.
Length: 402279 (393K) (unauthoritative)

libsigsegv-2.10.tar.gz                100%[========================================================================>] 392.85K   701KB/s   in 0.6s   

2016-01-27 10:12:14 (701 KB/s) - 'libsigsegv-2.10.tar.gz' saved [402279]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...

Build Tools:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc -m64
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
libsigsegv failed to install: `./configure --libdir=/usr/local/lib64/ CC="gcc -m64" CFLAGS=" -fPIC"` exited with 77
chronos@localhost /usr/local/bin $ crew update
error: cannot open .git/FETCH_HEAD: Permission denied

fatal: Unable to create '/usr/local/lib/crew/.git/index.lock': Permission denied
Package lists, crew, and library updated.
Checking for package updates...

ruby could be updated from 2.0.0p247 to 2.0.0p247-chromeos1

Run 'crew upgrade' to upgrade everything or 'crew upgrade <packageName>' to upgrade a specific package.
chronos@localhost /usr/local/bin $ sudo crew update
remote: Counting objects: 46, done.
remote: Total 46 (delta 25), reused 25 (delta 25), pack-reused 21
Unpacking objects: 100% (46/46), done.
From https://github.com/skycocker/chromebrew
 * branch            master     -> FETCH_HEAD
   6040131..85f6b7e  master     -> origin/master
HEAD is now at 85f6b7e Merge pull request #137 from thedamian/master
Package lists, crew, and library updated.
Checking for package updates...

ruby could be updated from 2.0.0p247 to 2.0.0p247-chromeos1

Run 'crew upgrade' to upgrade everything or 'crew upgrade <packageName>' to upgrade a specific package.
chronos@localhost /usr/local/bin $ sudo crew install libsigsegv
Found libsigsegv, version 2.10
Found libsigsegv, version 2.10
No precompiled binary available for your platform, downloading source...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2016-01-27 10:52:01--  ftp://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.10.tar.gz
           => 'libsigsegv-2.10.tar.gz'
Resolving ftp.gnu.org... 208.118.235.20
Connecting to ftp.gnu.org|208.118.235.20|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /gnu/libsigsegv ... done.
==> SIZE libsigsegv-2.10.tar.gz ... 402279
==> PASV ... done.    ==> RETR libsigsegv-2.10.tar.gz ... done.
Length: 402279 (393K) (unauthoritative)

libsigsegv-2.10.tar.gz                100%[========================================================================>] 392.85K   667KB/s   in 0.6s   

2016-01-27 10:52:03 (667 KB/s) - 'libsigsegv-2.10.tar.gz' saved [402279]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...

Build Tools:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc -m64
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
libsigsegv failed to install: `./configure --libdir=/usr/local/lib64/ CC="gcc -m64" CFLAGS=" -fPIC"` exited with 77
chronos@localhost /usr/local/bin $ ls -ld
drwxr-xr-x 2 root root 4096 Jan 27 10:12 .
chronos@localhost /usr/local/bin $ ls -ld ..
drwxr-xr-x 14 root root 4096 Jan 12 14:10 ..
chronos@localhost /usr/local/bin $ ls -ld ../tmp/
drwxr-xr-x 3 root root 4096 Jan 12 14:07 ../tmp/
chronos@localhost /usr/local/bin $ 
```

**Comment by dhasenan** [comment] 2016-01-27 19:01
As for trying to compile a 64-bit executable on a 32-bit OS, I wrote a program to detect pointer size. It says that sizeof(void*) is 8. /proc/cpuinfo says that the cpu is an Intel(R) Celeron(R) CPU 847 @ 1.10GHz.

**Comment by thedamian** [comment] 2016-02-03 23:37
I made a suggestion for this fix. Look into the config.log for that libsigsegv project.

If you see a missing reference to : libmpc.so.2 I think I may have a quick and dirty trick to fix it here: https://github.com/skycocker/chromebrew/issues/142

Tell me first if that's the error you're getting.

**Comment by lyxell** [comment] 2016-12-14 18:19
I believe this to be a duplicate of #103 
Please reopen if I'm incorrect.

**Closed by lyxell** 2016-12-14 18:19 UTC
