### ISSUE TITLE
readline causes error: undefined symbol: rl_signal_event_hook

### ISSUE THREAD

**Issue by hsharrison** [skycocker/chromebrew#190] opened 2016-06-22 16:21 UTC
I get this error when trying to run bash: `bash: symbol lookup error: bash: undefined symbol: rl_signal_event_hook`

`sudo crew remove readline` fixes it and doesn't seem to break anything. So I have to run this after every time I install something with a readline dependency.

I think the problem stems from a mismatch between the crew readline and the one that ChromeOS's original bash was built with. There's probably a way to properly separate the libraries, but that's over my head.

**Comment by thedamian** [comment] 2016-06-22 17:54
I saw this in the dev channel. This "bash: undefined symbol: rl_signal_event_hook" is a problem with the latest version of bash 4.3

Does anyone know how to fix this?

@hsharrison are you in the dev channel on your chromebook?

https://www.google.com/search?q=bash%3A+undefined+symbol%3A+rl_signal_event_hook

**Comment by hsharrison** [comment] 2016-06-22 19:05
I'm on beta. As I said, `sudo crew remove readline` fixed it for me and doesn't seem to cause any problems.

**Comment by hsharrison** [comment] 2016-06-22 19:07
@thedamian Is there a specific search result you're trying to draw attention to with that link?

**Comment by thedamian** [comment] 2016-06-22 19:31
The error is for more than just for this package. 
If you've fixed the issue please close it or let's rename it to the rl_singal_event_hook error because as the code from the "DEV" Channel rolls into the regular channel we'll all see these errors throughout our code.

I take it bash 4.3 has gone to the beta channel already so this event will come soon enough.

**Comment by hsharrison** [comment] 2016-06-22 20:24
The error stems from a mismatch between the version of readline that bash was compiled with and the version of readline installed on the computer. That's why others have experienced it in different contexts.

**Comment by lyxell** [comment] 2016-06-22 22:13
Some packages depend on readline to be built.

Possible solutions:
* Use static libraries for readline
* Use the system readline

**Comment by mike-pomodoro** [comment] 2016-07-23 18:28
I powerwashed my Acer c720 chromebook. After installing chromebrew, bash gives this error:
> chronos@localhost / $ bash
> bash: symbol lookup error: bash: undefined symbol: rl_signal_event_hook

Copy of shell output:  http://pastebin.com/8iUjFaBi

Seems bash (and a bunch of other commands) breaks anytime chromebrew is installed :(

Removing readline does get bash to work again:
> sudo crew remove readline

**Comment by faddah** [comment] 2016-07-25 22:50
the `sudo crew remove readline` did it for me — i used that and i suddenly didn't get`error: undefined symbol: rl_signal_event_hook` issue anymore, especially on npm installed packages that should run fine on their own, like `n` or `http-server` or `json-server`. they all work now, didn't before, kept getting the error with `rl_signal_event_hook`. as stated above, this seems to be a conflict between what is installed in packages as `readline` and the latest version of bash 4.3. until that is resolved in bash or readline or both, for now, i would suggest putting in the FAQ somewhere to `sudo crew remove readline` to fix this. my 2 cents, in any case.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by thedamian** [comment] 2016-07-27 16:41
Readline updated to 6.3 to fix the "undefined symbol: rl_signal_event_hook "

https://github.com/skycocker/chromebrew/pull/197

@hsharrison  please close this issue once you've tested the solution.
(if you don't know what to do is copy the readline.rb from that pull, copy it to your /usr/local/lib/crew/packages directory and then do a 'crew upgrade readline')

Enjoy!

**Comment by lyxell** [comment] 2016-07-28 11:57
@thedamian Your solution will break if Chrome OS updates readline again. A better solution would be to either use the system readline or a static version of readline.

**Comment by thedamian** [comment] 2016-07-28 12:09
the issue IS with our version of readline. We need the readline package for some other packaged here and the version checked in doesn't work well with the current version of bash installed. 

So correct me where I'm wrong to upgrade readline.

**Comment by lyxell** [comment] 2016-07-28 12:36
The issue started to occur when Google updated the system version of readline inside Chrome OS, making it mismatch the one installed by Chromebrew. If you update it again, it will work, but it would break if Google decides to update readline again. To make sure it won't break again, one could either use the system version of readline (not sure that this is possible) or only install the static libraries of readline.

Which packages would break if we don't install readline at all?

**Comment by mike-pomodoro** [comment] 2016-08-14 03:41
Just installed chromebrew few minutes ago:

> wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash

But still getting this error:

> chronos@localhost ~$ bash
> bash: symbol lookup error: bash: undefined symbol: rl_signal_event_hook

Laptop was powerwashed few minutes before installing Chromebrew (so it's freshly installed with nothing else mucking up the configuration):
> Version 52.0.2743.116 (64-bit)
> Platform 8350.68.0 (Official Build) stable-channel peppy
> Firmware Google_Peppy.4389.93.0

Am I missing something or did this issue not get fixed?

**Comment by cstrouse** [comment] 2016-12-23 07:55
I went to do some work with XML parsing on the command line this evening and noticed that our version of readline also breaks the xmllint tool in the same fashion.

```
chronos@localhost / $ xmllint 
xmllint: symbol lookup error: /usr/local/lib/libreadline.so.6: undefined symbol
```

**Comment by jam7** [comment] 2017-08-07 07:23
This error caused by readline version mismatch often.
To solve this problem, we need to modify version of readline which is installed by readline.rb.

I think the version is corrected last sometime in the last year.  I'll close this issue if there is no other reports or opinions.  Thanks.

**Closed** 2017-08-11 10:39 UTC
