### ISSUE TITLE
The chromebrew installer does not calculate build dependencies when it finds no precompiled binaries

### ISSUE THREAD

**Issue by QueenPew** [skycocker/chromebrew#5811] opened 2021-05-25 18:12 UTC
## Description
When installing chromebrew, the installer script does not check for build dependencies when finding no precompiled binaries for that packages, this immediately fails on a "normal" installation.
```shell
curl -Ls git.io/vddgY | bash
```

Output:
```shell
# Skipping some lines for brevity
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
No precompiled binary available for your platform, downloading source...
######################################################################## 100.0%
Archive downloaded.
Unpacking archive using 'tar', this may take a while...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
mkdir: created directory 'glibc_build'
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/usr/local/tmp/crew/glibc.20210525174200.dir/glibc-2.23/glibc_build':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
glibc failed to install: `../configure --prefix=/usr/local --libdir=/usr/local/lib --with-headers=/usr/local/include --disable-werror --disable-sanity-checks --enable-shared --enable-obsolete-rpc libc_cv_forced_unwind=yes --without-selinux` exited with 1
```

## Versions and system information
ChromeOS: 
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7358984
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v7keys
CHROMEOS_RELEASE_BRANCH_NUMBER=0
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R92-13975.0.0
CHROMEOS_RELEASE_BUILD_NUMBER=13975
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=92
CHROMEOS_RELEASE_DESCRIPTION=13975.0.0 (Official Build) dev-channel hana 
CHROMEOS_RELEASE_KEYSET=mp-v7
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=dev-channel
CHROMEOS_RELEASE_VERSION=13975.0.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13975.0.0
Model: Lenovo C330

Architecture: `uname -m`
aarch64 (with armhf userland)

What I think needs to be done:
- [ ] Implement a minimal version of Chromebrew's installer script (so it fetches a minimum of packages) so breakage like this could be less often 
- [ ]  Implement the build dependency checker in chromebrew's installer script
## Additionnal notes
glibc also fails to detect the architecture, per https://github.com/skycocker/chromebrew/issues/5398#issuecomment-840891103

**Comment by satmandu** [comment] 2021-05-26 03:37
There are glibc binaries available for `armv7l`  using logic predicated upon matching the glibc version on the target system... but that only works for glibc version 2.27 for `armv7l`. Your system is on dev channel M92, which may have moved to glibc 2.32 as per https://groups.google.com/a/chromium.org/g/chromium-os-dev/c/WUnFZJXP2fU ... 

so we will need to update this package for chromebrew to work on M92...

@uberhacker We knew this was coming...

**Comment by uberhacker** [comment] 2021-05-26 03:45
Also, as stated in README.md:
```
The beta, dev, and Canary channels are not supported and should not be used with Chromebrew. Failure to take notice of this will cause major issues with your Chromebrew installation. 
```
In other words, we only support the stable channel.

**Comment by heavygabriel** [comment] 2021-05-26 23:02
oh, I have completely forgot that I'm on the developper channel!
Should I close this thread as I'm on an unsupported channel?

**Comment by satmandu** [comment] 2021-05-26 23:17
@heavygabriel Would you be so kind as to run `ls /lib/ld*` and tell us what you get?

I'm assuming that M92 has glibc 2.32, but I just want a confirmation...

**Comment by heavygabriel** [comment] 2021-05-27 12:20
@satmandu 
```shell
$ ls /lib/ld*
rwxr-xr-x. 1 root root 136376 May 19 04:32 /lib/ld-2.32.so
lrwxrwxrwx. 1 root root     10 May 19 04:32 /lib/ld-linux-armhf.so.3 -> ld-2.32.so
```
I can confirm that M92 has glibc 2.32.

**Comment by satmandu** [comment] 2021-05-27 15:18
Fantastic. Any chance I can get you to dump one of the ROOT partitions so we can use it to try to get some test builds running? (I don't have arm64 ChromeOS hardware, so I use recovery images anyways to build, but recovery images are only available publicly for Stable builds.

**Comment by satmandu** [comment] 2021-05-27 15:20
@heavygabriel Instructions would basically be here: https://github.com/skycocker/chromebrew/issues/5443#issuecomment-819672073

**Comment by satmandu** [comment] 2021-05-27 15:21
I should be able to get the ROOTFS for M92 for x86_64 next week or so when that hits Beta channel.

**Comment by heavygabriel** [comment] 2021-05-27 18:21
> Fantastic. Any chance I can get you to dump one of the ROOT partitions so we can use it to try to get some test builds running?

@satmandu: You could also build a ChromiumOS image(arm64...) and extract the ROOT partition from it.

**Comment by satmandu** [comment] 2021-05-28 03:14
@heavygabriel Not ROOT, sorry. I meant  one of the two Read Only RootFS partitions, specifically Partition 3, which is RootFS A.

(User info is stored in the separate "stateful partition") See https://www.chromium.org/chromium-os/chromiumos-design-docs/disk-format

This of course assumes that you haven't turned off RootFS verification and made it read/write.

But no worries if you're not comfortable with that. We'll wait until we find some other way...

**Comment by heavygabriel** [comment] 2021-05-28 13:14
@satmandu: Here's a ChromiumOS arm64 RootFS partition: https://drive.google.com/file/d/1KusVNEo7NNpI3m6obsvOmU1YU8wn2N2P/view?usp=sharing
(There's instructions on how to build ChromiumOS [here](https://chromium.googlesource.com/chromiumos/docs/+/main/developer_guide.md)

**Comment by satmandu** [comment] 2021-05-28 13:16
> @satmandu: Here's a ChromiumOS arm64 RootFS partition: https://drive.google.com/file/d/1KusVNEo7NNpI3m6obsvOmU1YU8wn2N2P/view?usp=sharing
> (There's instructions on how to build ChromiumOS [here](https://chromium.googlesource.com/chromiumos/docs/+/main/developer_guide.md))

Is that from your machine? (I need a M92 RootFS to test with glibc 2.32. I already have a M90 Arm64 RootFS.)

**Comment by heavygabriel** [comment] 2021-05-28 13:17
No, but it's a canary/dev ChromiumOS arm64 RootFS partition. Should be good enough.

**Comment by satmandu** [comment] 2021-05-29 01:10
Hmm... This is what I see @uberhacker 
[M93du.aarch64.txt](https://github.com/skycocker/chromebrew/files/6563842/M93du.aarch64.txt)

It looks like there's some version of an aarch64 userspace for a change, but I'm not seeing `/bin/bash` in this dump.

@heavygabriel Can you tell me what `mount` gives you?

Also I need what `which bash` gives you.

**Comment by uberhacker** [comment] 2021-05-29 01:15
There's that lovely lib64 directory I see.

**Comment by heavygabriel** [comment] 2021-05-30 04:17
@satmandu: From what I've seen, that arm64 thing is non-standard, every ChromeOS build uses armhf instead of arm64.
Also, I've fixed my builds
[Here is an armhf ROOT partition](https://drive.google.com/file/d/1KusVNEo7NNpI3m6obsvOmU1YU8wn2N2P/view?usp=sharing)  and [here is an arm64 ROOT partition](https://drive.google.com/file/d/1AYu3UKPJHm4t6oJm5EbY0Z_imG_Tu2RW/view?usp=sharing) (You might ask "why can't you attach files via GitHub?", well, GitHub does not like 500MB files)

**Closed** 2022-05-03 02:25 UTC
