### ISSUE TITLE
Package Request: rdesktop or freerdp

### ISSUE THREAD

**Issue by jwhipp** [skycocker/chromebrew#99] opened 2015-09-09 16:35 UTC
Chromeos lacks a decent RDP app.   Not sure how X apps work though, so this really a just a feeler to see if it's even possible to compile and run them on ChromeOS

**Comment by elkangaroo** [comment] 2015-09-17 17:40
Duplicate of #66 .

**Closed** 2015-09-23 14:23 UTC
