### ISSUE TITLE
[Mesa] Failed to build

### ISSUE THREAD

**Issue by leonbollerup** [skycocker/chromebrew#4713] opened 2020-12-04 22:39 UTC
chronos@localhost ~ $ crew upgrade mesa -s
mesa: Open-source implementation of the OpenGL specification
https://www.mesa3d.org
version 20.3.0
Updating mesa...
Downloading source...
############################################################################################################################################################# 100.0%############################################################################################################################################################# 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Found existing installation: Mako 1.1.3
Uninstalling Mako-1.1.3:
  Successfully uninstalled Mako-1.1.3
Found existing installation: MarkupSafe 1.1.1
Uninstalling MarkupSafe-1.1.1:
  Successfully uninstalled MarkupSafe-1.1.1
Collecting Mako
  Using cached Mako-1.1.3-py2.py3-none-any.whl (75 kB)
Collecting MarkupSafe>=0.9.2
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Installing collected packages: MarkupSafe, Mako
  WARNING: The script mako-render is installed in '/usr/local/tmp/crew/dest/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Mako-1.1.3 MarkupSafe-1.1.1
WARNING: You are using pip version 20.2.1; however, version 20.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python3.8 -m pip install --upgrade pip' command.
Collecting Mako
  Using cached Mako-1.1.3-py2.py3-none-any.whl (75 kB)
Collecting MarkupSafe>=0.9.2
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Installing collected packages: MarkupSafe, Mako
Successfully installed Mako-1.1.3 MarkupSafe-1.1.1
WARNING: You are using pip version 20.2.1; however, version 20.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python3.8 -m pip install --upgrade pip' command.

mesa failed to install: `meson -Dprefix=/usr/local -Dlibdir=/usr/local/lib64 -Dmandir=/usr/local/share/man -Dbuildtype=release builddir` exited with 127

**Comment by satmandu** [comment] 2020-12-05 00:38
Can you try after ```crew install gcc10```?

**Comment by leonbollerup** [comment] 2020-12-05 07:23
Done and upgraded pip also..
--

chronos@localhost ~ $ crew upgrade mesa
mesa: Open-source implementation of the OpenGL specification
https://www.mesa3d.org
version 20.3.0
Updating mesa...
No precompiled binary available for your platform, downloading source...
############################################################################################################################################################# 100.0%############################################################################################################################################################# 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Found existing installation: Mako 1.1.3
Uninstalling Mako-1.1.3:
  Successfully uninstalled Mako-1.1.3
Found existing installation: MarkupSafe 1.1.1
Uninstalling MarkupSafe-1.1.1:
  Successfully uninstalled MarkupSafe-1.1.1
Collecting Mako
  Using cached Mako-1.1.3-py2.py3-none-any.whl (75 kB)
Collecting MarkupSafe>=0.9.2
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Installing collected packages: MarkupSafe, Mako
  WARNING: The script mako-render is installed in '/usr/local/tmp/crew/dest/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Mako-1.1.3 MarkupSafe-1.1.1
Collecting Mako
  Using cached Mako-1.1.3-py2.py3-none-any.whl (75 kB)
Collecting MarkupSafe>=0.9.2
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Installing collected packages: MarkupSafe, Mako
Successfully installed Mako-1.1.3 MarkupSafe-1.1.1
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: cannot import name 'load_entry_point' from 'pkg_resources' (unknown location)
mesa failed to install: `meson -Dprefix=/usr/local -Dlibdir=/usr/local/lib64 -Dmandir=/usr/local/share/man -Dbuildtype=release builddir` exited with 1

**Comment by uberhacker** [comment] 2020-12-06 01:41
Duplicate of #4705.

**Closed** 2020-12-08 02:49 UTC
Labels: bug, duplicate
