### ISSUE TITLE
Installing nano fails

### ISSUE THREAD

**Issue by aghasemi** [skycocker/chromebrew#231] opened 2016-11-06 09:52 UTC
Here is the error

```
Found nano, version 2.3.6
Following packages also need to be installed: 
libsigsegv diffutils binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential ncurses 
Do you agree? [Y/n]
y
Proceeding...
Found libsigsegv, version 2.10
No precompiled binary available for your platform, downloading source...
--2016-11-06 10:50:45--  http://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.10.tar.gz
Resolving ftp.gnu.org... 208.118.235.20
Connecting to ftp.gnu.org|208.118.235.20|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 402279 (393K) [application/x-gzip]
Saving to: 'libsigsegv-2.10.tar.gz'

libsigsegv-2.10.tar.gz                    100%[=====================================================================================>] 392.85K   461KB/s    in 0.9s    

2016-11-06 10:50:48 (461 KB/s) - 'libsigsegv-2.10.tar.gz' saved [402279/402279]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...

Build Tools:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc -m64
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
libsigsegv failed to install: `./configure --libdir=/usr/local/lib64/ CC="gcc -m64" CFLAGS=" -fPIC"` exited with 77
```

**Comment by aghasemi** [comment] 2016-11-06 09:54
Here the config.log output:

```
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by configure, which was
generated by GNU Autoconf 2.68.  Invocation command line was

  $ ./configure --libdir=/usr/local/lib64/ CC=gcc -m64 CFLAGS= -fPIC

## --------- ##
## Platform. ##
## --------- ##

hostname = localhost
uname -m = x86_64
uname -r = 4.4.14+
uname -s = Linux
uname -v = #1 SMP Sun Oct 30 23:30:16 UTC 2016

/usr/bin/uname -p = Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/linuxbrew/bin
PATH: /usr/local/linuxbrew/sbin
PATH: /home/chronos/user/.linuxbrew/bin
PATH: /home/chronos/user/.linuxbrew/bin
PATH: /home/chronos/user/.linuxbrew/bin
PATH: /usr/local/.linuxbrew/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /opt/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2335: checking for a BSD-compatible install
configure:2403: result: /usr/bin/install -c
configure:2414: checking whether build environment is sane
configure:2464: result: yes
configure:2605: checking for a thread-safe mkdir -p
configure:2644: result: /bin/mkdir -p
configure:2657: checking for gawk
configure:2687: result: no
configure:2657: checking for mawk
configure:2673: found /usr/bin/mawk
configure:2684: result: mawk
configure:2695: checking whether make sets $(MAKE)
configure:2717: result: yes
configure:2850: checking for gcc
configure:2877: result: gcc -m64
configure:3106: checking for C compiler version
configure:3115: gcc -m64 --version >&5
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3126: $? = 0
configure:3115: gcc -m64 -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --enable-languages=c,c++
Thread model: posix
gcc version 4.8.1 (GCC) 
configure:3126: $? = 0
configure:3115: gcc -m64 -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3126: $? = 1
configure:3115: gcc -m64 -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3126: $? = 1
configure:3146: checking whether the C compiler works
configure:3168: gcc -m64  -fPIC   conftest.c  >&5
/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/cc1: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
configure:3172: $? = 1
configure:3210: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "libsigsegv"
| #define VERSION "2.10"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3215: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
configure:3217: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_env_CC_set=set
ac_cv_env_CC_value='gcc -m64'
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value=' -fPIC'
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=mawk
ac_cv_prog_ac_ct_CC='gcc -m64'
ac_cv_prog_make_make_set=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /usr/local/tmp/crew/libsigsegv-2.10/build-aux/missing --run aclocal-1.11'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='${SHELL} /usr/local/tmp/crew/libsigsegv-2.10/build-aux/missing --run tar'
AR=''
AUTOCONF='${SHELL} /usr/local/tmp/crew/libsigsegv-2.10/build-aux/missing --run autoconf'
AUTOHEADER='${SHELL} /usr/local/tmp/crew/libsigsegv-2.10/build-aux/missing --run autoheader'
AUTOMAKE='${SHELL} /usr/local/tmp/crew/libsigsegv-2.10/build-aux/missing --run automake-1.11'
AWK='mawk'
CC='gcc -m64'
CCDEPMODE=''
CFG_HANDLER=''
CFG_LEAVE=''
CFG_STACKVMA=''
CFLAGS=' -fPIC'
CPP=''
CPPFLAGS=''
CYGPATH_W='echo'
CYGWIN_FALSE=''
CYGWIN_TRUE=''
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
ENABLE_EFAULT_FALSE=''
ENABLE_EFAULT_TRUE=''
EXEEXT=''
FAULT_CONTEXT=''
FAULT_CONTEXT_INCLUDE=''
FGREP=''
GREP=''
HAVE_SIGSEGV_RECOVERY=''
HAVE_STACK_OVERFLOW_RECOVERY=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
MAKEINFO='${SHELL} /usr/local/tmp/crew/libsigsegv-2.10/build-aux/missing --run makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/bin/mkdir -p'
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='libsigsegv'
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_URL=''
PACKAGE_VERSION=''
PATH_SEPARATOR=':'
PLATFORM=''
RANLIB=''
RELOCATABLE=''
SED=''
SET_MAKE=''
SHELL='/bin/bash'
STRIP=''
VERSION='2.10'
ac_ct_AR=''
ac_ct_CC='gcc -m64'
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__quote=''
am__tar='${AMTAR} chf - --owner=root --group=root "$$tardir"'
am__untar='${AMTAR} xf -'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE}'
dvidir='${docdir}'
exec_prefix='NONE'
host=''
host_alias=''
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /usr/local/tmp/crew/libsigsegv-2.10/build-aux/install-sh'
libdir='/usr/local/lib64'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='/bin/mkdir -p'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "libsigsegv"
#define VERSION "2.10"

configure: exit 77
```

**Comment by lyxell** [comment] 2016-12-13 22:56
Duplicate of #103

**Closed by lyxell** 2016-12-13 22:56 UTC
