### ISSUE TITLE
Texlive - tlmgr cannot find wget

### ISSUE THREAD

**Issue by doggybuns** [skycocker/chromebrew#2695] opened 2018-09-23 01:34 UTC
## Description
Using tlmgr (installed through texlive) returns a wget error even though it is installed

```shell
tlmgr install latexmk
```

Output:
```shell
/usr/local/share/texlive/2017/bin/x86_64-linux/tlmgr: Initialization failed (in setup_unix_one):
/usr/local/share/texlive/2017/bin/x86_64-linux/tlmgr: could not find a usable wget.
/usr/local/share/texlive/2017/bin/x86_64-linux/tlmgr: Please install wget and try again.
tlmgr: Couldn't set up the necessary programs.
Installation of packages is not supported.
Please report to texlive@tug.org.
Use of uninitialized value $r in split at /usr/local/share/texlive/2017/tlpkg/TeXLive/TLUtils.pm line 4147.
tlmgr: Cannot find main repository, you have to tag one as main!
```

## Versions and system information
chromebrew: `1.0.3`
Architecture: `x86_64`

**Comment by JL2210** [comment] 2018-09-23 13:03
Can you please try `crew remove wget && crew update && crew upgrade && crew install wget` and try again?

**Comment by JL2210** [comment] 2018-09-23 13:04
After that, can you give me the output of `which wget`?

**Comment by doggybuns** [comment] 2018-09-23 18:58
The same issue persists.  
`which get` outputs `/usr/local/bin/wget`

**Comment by JL2210** [comment] 2018-09-30 17:11
@doggybuns: I can't reproduce this. Could you try reinstalling `texlive`?

**Comment by doggybuns** [comment] 2018-10-02 01:43
The issue still persists. What does `which wget` output for you?

**Comment by skiman6010** [comment] 2018-10-02 03:05
I was able to reproduce on x86_64 as well.

@JL2210 What architecture are you not able to reproduce on? I'm curious.

**Comment by JL2210** [comment] 2018-10-02 11:40
x86_64. I tried `tlmgr install latexmk` on a fresh crew. I didn't get the error he did.

**Comment by JL2210** [comment] 2018-10-02 12:06
`/usr/local/bin/wget`

**Comment by JL2210** [comment] 2018-10-06 02:32
Could `zsh` be the problem? I'm using bash and I had an unrelated issue about the `2018` version.

**Comment by doggybuns** [comment] 2018-10-06 04:03
After installing zsh again, tlmgr still seems to be working fine. 

This is strange since I don't know what I did differently that could have solved it. But I am glad it resolved itself. Now I can do all my math assignments from my Chromebook.

**Comment by JL2210** [comment] 2018-10-06 16:46
Glad it works for you. Could we close this?

**Closed** 2018-10-09 04:48 UTC
Labels: bug, x86_64
