### ISSUE TITLE
VS Code doesn't load

### ISSUE THREAD

**Issue by caglewebsolutions** [skycocker/chromebrew#2998] opened 2018-12-26 22:16 UTC
## Description
VS Code never loads. Sommelier is running, but for whatever reason, Code never shows up. I'm just dropped back to the command propmpt. 

If you executed a specific command:
```shell
code
```

Output:
```shell

```

## Versions and system information
chromebrew: `1.0.6`

ChromeOS: `CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_RELEASE_BOARD=candy-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=59
CHROMEOS_RELEASE_BUILDER_PATH=candy-release/R71-11151.59.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.59.0 (Official Build) stable-channel candy 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.59.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.59.0`

Model: Dell Chromebook 11 3120

Architecture: `x86_64`

**Comment by JL2210** [comment] 2018-12-26 22:31
Do you have Internet? Try to connect while VSCode is running. This looks like an updater issue. If that doesn't work, try running with no Internet.

**Comment by JL2210** [comment] 2018-12-26 22:32
Why'd you change your log? Give me the full output.

**Comment by caglewebsolutions** [comment] 2018-12-26 22:34
I changed my log because I didn't initially have it all copied like I thought I did. What you see now is the full output.

**Comment by caglewebsolutions** [comment] 2018-12-26 22:36
It seems to be doing the same thing whether I'm connected to the internet or not.

**Comment by JL2210** [comment] 2018-12-26 22:36
Give me the file `log` from the command `cd ~/Downloads && code &>log`

**Comment by caglewebsolutions** [comment] 2018-12-26 22:38
The log file ends up being blank.

**Comment by JL2210** [comment] 2018-12-26 22:39
And run `mkdir -p /usr/local/var/run/dbus; ln -s /var/run/dbus/system_bus_socket /usr/local/var/run/dbus` beforehand.

**Comment by caglewebsolutions** [comment] 2018-12-26 22:39
Oh hold, let me go back for some reason I'm missing part of that command you gave me.

**Comment by caglewebsolutions** [comment] 2018-12-26 22:40
Oh, need to run those commands beforehand now. ok

**Comment by caglewebsolutions** [comment] 2018-12-26 22:42
[log.txt](https://github.com/skycocker/chromebrew/files/2710965/log.txt)

**Comment by JL2210** [comment] 2018-12-26 22:43
`sommelier -X code --verbose`?

**Comment by caglewebsolutions** [comment] 2018-12-26 22:46
Warning: Unknown scale factor: 1111
Warning: Unknown scale factor: 952
Warning: Unknown scale factor: 909
Warning: Unknown scale factor: 870
Warning: Unknown scale factor: 833
Warning: Unknown scale factor: 769
Warning: Unknown scale factor: 667
[9287:1226/174542.296630:WARNING:audio_manager.cc(295)] Multiple instances of AudioManager detected
[9287:1226/174542.305717:WARNING:audio_manager.cc(254)] Multiple instances of AudioManager detected
[9314:1226/174542.564796:ERROR:gl_surface_glx.cc(406)] glxQueryVersion failed
[9314:1226/174542.565660:ERROR:gl_initializer_x11.cc(148)] GLSurfaceGLX::InitializeOneOff failed.
[9314:1226/174542.581041:ERROR:gpu_child_thread.cc(324)] Exiting GPU process due to errors during initialization
[main 5:45:43 PM] Starting VS Code
[main 5:45:43 PM] from: /usr/local/share/code/resources/app
[main 5:45:43 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 5:45:43 PM] Resolving machine identifier...
[main 5:45:43 PM] Resolved machine identifier: dd416edf421c2a8fdcce2de41a7bccb69b3874247fc4f1fbb41b153c18b7b068
[main 5:45:43 PM] update#setState idle

**Comment by JL2210** [comment] 2018-12-26 22:47
It looks like we need GLX.

**Comment by caglewebsolutions** [comment] 2018-12-26 22:54
OK. Is there a particular package? No package called GLX, and I tried whatprovides and all that would provide it is installed.

**Comment by JL2210** [comment] 2018-12-26 22:58
`crew install glproto libepoxy libxcb mesa xcb_proto xorg_proto`

**Comment by caglewebsolutions** [comment] 2018-12-26 22:59
Those are all installed though. I know because I just determined that before you told me to run that command.

**Comment by caglewebsolutions** [comment] 2018-12-26 23:00
I mean, I could uninstall and reinstall those packages.

**Comment by JL2210** [comment] 2018-12-26 23:00
Let me Google those errors.

**Comment by JL2210** [comment] 2018-12-26 23:03
I give up. Time to compile VSCode from source.

**Comment by caglewebsolutions** [comment] 2018-12-26 23:05
I know it had previously been working when I had my Chromebook on the development channel and beta channel. I don't know if that helps at all. It stopped working when I moved to the stable channel and reinstalled Code (and other Linux software).

**Comment by JL2210** [comment] 2018-12-26 23:07
That shouldn't matter if we build from source.

**Comment by caglewebsolutions** [comment] 2018-12-26 23:09
ok

**Comment by caglewebsolutions** [comment] 2018-12-27 06:31
Updated VS Code but still isn't working.

**Comment by caglewebsolutions** [comment] 2018-12-27 06:34
Also tried with --verbose and getting the same results.

**Comment by skiman6010** [comment] 2018-12-27 16:18
This wasn't fixed by the update. 

Can you try uninstalling and reinstalling these packages. `glproto libepoxy libxcb mesa xcb_proto xorg_proto`?

**Comment by skiman6010** [comment] 2018-12-27 16:32
@JL2210 I'm running Code fine with the newest `sommelier` and `Code` that was pushed. I will expect a PR from you  now that fixes your issues without breaking my install. :)

**Comment by caglewebsolutions** [comment] 2018-12-27 17:16
I'll try doing that when I get a chance. I'm about to head into work. Should be able to uninstall and reinstall those packages this evening.

**Comment by caglewebsolutions** [comment] 2018-12-27 22:36
I still don't have Code working after doing that.

**Comment by caglewebsolutions** [comment] 2018-12-27 22:38
I'm giving -S a try and see if that might do the trick.

**Comment by caglewebsolutions** [comment] 2018-12-27 23:31
And still not working.

**Comment by JL2210** [comment] 2018-12-27 23:53
@skiman6010 isn't having any problem. Any suggestions?

**Comment by caglewebsolutions** [comment] 2018-12-28 00:13
Well I'm moving onto Sublime Text at this point.

**Comment by skiman6010** [comment] 2018-12-28 00:37
One more shot in the dark, can you remove and reinstall sommelier with the -s option? `crew remove sommelier && crew install sommelier -s`? After that I'm not sure how to help since I can't reproduce.

**Comment by caglewebsolutions** [comment] 2018-12-28 00:41
Maybe later. Right now I've got other things I need to focus on.

**Comment by JL2210** [comment] 2018-12-28 00:44
@skiman6010, maybe you should try reinstalling Chromebrew. Everybody else
is having this issue.
As a side note, 'crew install -s sommelier' doesn't help. I already tried
it.

**Comment by caglewebsolutions** [comment] 2018-12-28 01:01
I'm thinking I might have to reinstall Chromebrew too. Is there a specific command for reinstalling Chromebrew or is it just like the initial install?

**Comment by JL2210** [comment] 2018-12-28 01:43
Can you send your system info?

**Comment by skiman6010** [comment] 2018-12-28 01:47
```$ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5167872
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_RELEASE_BOARD=samus-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=59
CHROMEOS_RELEASE_BUILDER_PATH=samus-release/R71-11151.59.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.59.0 (Official Build) beta-channel samus 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=11151.59.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.59.0```

Yes I'm on the beta channel but it is still 71. I'm waiting for 72 to roll out. I feel like that wouldn't be the reason Code is working but let's keep that in mind. 

`x86_64` is my arch.

**Comment by JL2210** [comment] 2018-12-28 01:48
OK. Let's start with the basics. FAQ entry:
```
Q: I'm having miscellaneous errors when installing packages on the beta, dev, or canary channels. What do I do?

A: Installing Chromebrew on the beta, dev, or canary channels is NOT supported. Revert back to the stable channel and try again.
```

**Comment by JL2210** [comment] 2018-12-28 01:51
If you could revert to stable and try again, that would be great.

**Comment by skiman6010** [comment] 2018-12-28 01:52
@JL2210 I want you to really look closely at my system information and at the information posted at the top. Now really really really look at the release version. Does 11151.59.0 = 11151.59.0?

**Comment by JL2210** [comment] 2018-12-28 01:53
All right. You win. Can you give me the output of `uname -a`?

**Comment by skiman6010** [comment] 2018-12-28 01:54
`Linux localhost 3.14.0 #1 SMP PREEMPT Mon Dec 10 23:52:18 PST 2018 x86_64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz GenuineIntel GNU/Linux`

**Comment by JL2210** [comment] 2018-12-28 01:56
Hmm. You have an OLDER kernel than me, so that's not the issue.

**Comment by sajjaadf** [comment] 2018-12-28 02:54
I am getting the same type of error with the unofficial arm-vscode too.

-- SajjaadF

**Comment by JL2210** [comment] 2018-12-28 02:55
@sajjaadf You can update now. The package builds from source.

**Comment by sajjaadf** [comment] 2018-12-30 02:42
FINALY!!!!

**Comment by vincowl** [comment] 2019-01-02 01:51
Any news on this issue ? Having the same problem here on a fresh install : vscode cannot run given a GTK error (cannot open Display :0)

**Comment by JL2210** [comment] 2019-01-02 03:03
@vincowl Have you installed `sommelier` and run the **blue text** at the bottom? That might fix your issue.

**Comment by vincowl** [comment] 2019-01-02 08:52
@JL2210 Yes I did and apps like gimp, filezilla or inkscape are displaying in a normal way. I am trying to reinstall code using ```crew install -S code```.

**Comment by vincowl** [comment] 2019-01-02 12:20
Still this error message while running `code-oss` in a shell
```shell
(code-oss:4423): Gtk-WARNING **: 13:10:43.431: cannot open display: :0
```
Here is my `~/.bashrc`
```bash
# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
        # Shell is non-interactive.  Be done now!
        return
fi


# Put your fun stuff here.
export PAGER=/usr/local/bin/less
# Sommelier environment variables + daemon
# See https://github.com/dnschneid/crouton/wiki/Sommelier-(A-more-native-alternative-to-xiwi)
if [ ! -d /tmp/.X11-unix ]; then
mkdir /tmp/.X11-unix
fi
sudo chmod -R 1777 /tmp/.X11-unix
sudo chown root:root /tmp/.X11-unix
alias startsommelier="set -a && source ~/.sommelier.env && set +a && initsommelier"
# XDG Base Directory Specification Environment Variables
# See https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html.
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_DIRS=/usr/local/share
export XDG_CONFIG_DIRS=/usr/local/etc/xdg
export XDG_CACHE_HOME=$HOME/.cache
# nodebrew completion
if [ -f /usr/local/share/nodebrew/completions/bash/nodebrew-completion ]; then
  source /usr/local/share/nodebrew/completions/bash/nodebrew-completion
fi
export PATH=$HOME/.nodebrew/current/bin:$PATH

startsommelier
```
**Here are the packages I installed**. Everything is up to date.
[installed_packages.txt](https://github.com/skycocker/chromebrew/files/2720703/installed_packages.txt)


## Versions and system information
**chromebrew:** 1.0.6

**ChromeOS:** 
`CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5167872
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={B00DD0BC-D2C9-BAB4-E66C-81AE3F5A7CED}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={B00DD0BC-D2C9-BAB4-E66C-81AE3F5A7CED}
CHROMEOS_RELEASE_BOARD=cave-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=59
CHROMEOS_RELEASE_BUILDER_PATH=cave-release/R71-11151.59.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.59.0 (Official Build) stable-channel cave 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.59.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.59.0`

**Model:** Asus Flip C302CA

**Architecture:** x86_64

**Comment by JL2210** [comment] 2019-01-08 11:58
Try setting LIBRARY_PATH like we do in GCC.

**Comment by JL2210** [comment] 2019-02-09 23:27
@caglewebsolutions How does this work now? I pushed an update that hopefully fixed the issue.

**Closed** 2019-08-05 16:09 UTC
Labels: aarch64, arm, bug, x86_64
