### ISSUE TITLE
python27 install fails because openssl won't build

### ISSUE THREAD

**Issue by brucem1976** [skycocker/chromebrew#614] opened 2017-05-01 18:28 UTC
On Samsung Chromebook Plus:

Configured for linux-aarch64.
making all in crypto...
make[1]: Entering directory `/usr/local/tmp/crew/openssl-1.0.2k.tar.gz.dir/openssl-1.0.2k/crypto'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
/usr/local/bin/perl ../util/mkbuildinf.pl "gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM" "linux-aarch64" >buildinf.h
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o cryptlib.o cryptlib.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o mem.o mem.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o mem_dbg.o mem_dbg.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o cversion.o cversion.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o ex_data.o ex_data.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o cpt_err.o cpt_err.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o ebcdic.o ebcdic.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o uid.o uid.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o o_time.o o_time.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o o_str.o o_str.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o o_dir.o o_dir.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o o_fips.o o_fips.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o o_init.o o_init.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o fips_ers.o fips_ers.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM   -c -o armcap.o armcap.c
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -c   -c -o arm64cpuid.o arm64cpuid.S
arm64cpuid.S: Assembler messages:
arm64cpuid.S:4: Error: unknown architecture `armv8-a+crypto'

arm64cpuid.S:10: Error: ARM register expected -- `orr v15.16b,v15.16b,v15.16b'
arm64cpuid.S:11: Error: bad instruction `ret'
arm64cpuid.S:17: Error: ARM register expected -- `mrs x0,CNTVCT_EL0'
arm64cpuid.S:18: Error: bad instruction `ret'
arm64cpuid.S:24: Error: selected processor does not support ARM mode `aese v0.16b,v0.16b'
arm64cpuid.S:25: Error: bad instruction `ret'
arm64cpuid.S:31: Error: selected processor does not support ARM mode `sha1h s0,s0'
arm64cpuid.S:32: Error: bad instruction `ret'
arm64cpuid.S:38: Error: selected processor does not support ARM mode `sha256su0 v0.4s,v0.4s'
arm64cpuid.S:39: Error: bad instruction `ret'
arm64cpuid.S:44: Error: bad instruction `pmull v0.1q,v0.1d,v0.1d'
arm64cpuid.S:45: Error: bad instruction `ret'
make[1]: *** [arm64cpuid.o] Error 1
make[1]: Leaving directory `/usr/local/tmp/crew/openssl-1.0.2k.tar.gz.dir/openssl-1.0.2k/crypto'
make: *** [build_crypto] Error 1
openssl failed to install: `make -j6` exited with 2

**Comment by ntchambers** [comment] 2017-05-01 21:57
If you change `/usr/local/lib/crew/packages/openssl.rb` to match #577  does it work?

**Comment by brucem1976** [comment] 2017-05-02 04:44
Thanks that worked - but now I get:

No precompiled binary available for your platform, downloading source...
--2017-05-02 06:42:02-- https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
Resolving www.python.org... 151.101.172.223
Connecting to www.python.org|151.101.172.223|:443... connected.
*** Error in `wget': free(): invalid pointer: 0xb9112888 ***
Checksum mismatch :/ try again

**Comment by ntchambers** [comment] 2017-05-02 04:46
Oh nice. A bug in wget. It looks like it frees a null pointer, but not important. Can you show what is in `/usr/local/lib/crew/packages/python27.rb`?

**Comment by brucem1976** [comment] 2017-05-02 04:48
Sure

require 'package'

class Openssl < Package
  version '1.0.2k'

  source_url 'ftp://openssl.org/source/openssl-1.0.2k.tar.gz'
  source_sha1 '5f26a624479c51847ebd2f22bb9f84b3b44dcb44'

  depends_on 'perl'
  depends_on 'zlibpkg'

  def self.build
    system "./config", "--prefix=/usr/local", "--openssldir=/etc/ssl", "shared", "zlib-dynamic", "no-asm"
    system "make"
  end

  def self.install
    # installing using multi cores may cause empty libssl.so.1.0.0 or libcrypto.so.1.0.0 problem
    system "make", "-j1", "INSTALL_PREFIX=#{CREW_DEST_DIR}", "install"

    # remove all files pretended to install /etc/ssl (use system's /etc/ssl as is)
    system "rm", "-rf", "#{CREW_DEST_DIR}/etc"
  end

end

**Comment by brucem1976** [comment] 2017-05-02 04:49
Thanks - sure

equire 'package'

class Python27 < Package
  version '2.7.13-1'
  source_url 'https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz' # software source tarball url
  source_sha1 '18a8f30a0356c751b8d0ea6f76e764cab13ee046'                     # source tarball sha1 sum

  depends_on 'bz2'
  depends_on 'ncurses'
  depends_on 'openssl'

  def self.build                                                  # self.build contains commands needed to build the software from source
    system "./configure --prefix=/usr/local CPPFLAGS=\"-I/usr/local/include -I/usr/local/include/ncurses\" LDFLAGS=\"-L/usr/local/lib\" CFLAGS=\" -fPIC\" --with-ensurepip=install"
    system "make"                                                 # ordered chronologically
  end

  def self.install                                                # self.install contains commands needed to install the software on the target system
    system "make", "DESTDIR=#{CREW_DEST_DIR}", "install"          # remember to include DESTDIR set to CREW_DEST_DIR - needed to keep track of changes made to system
  end
end

**Comment by ntchambers** [comment] 2017-05-02 04:54
Ok, the sha1 is fine. Can you `crew install strace` and then `strace crew install python27`?

**Comment by brucem1976** [comment] 2017-05-02 04:56
Eek!

Found strace, version 4.16
No precompiled binary available for your platform, downloading source...
--2017-05-02 06:56:00--  https://downloads.sourceforge.net/project/strace/strace/4.16/strace-4.16.tar.xz
Resolving downloads.sourceforge.net... 216.34.181.59
Connecting to downloads.sourceforge.net|216.34.181.59|:443... connected.
*** Error in `wget': free(): invalid pointer: 0xba94c758 ***
Checksum mismatch :/ try again

**Comment by ntchambers** [comment] 2017-05-02 05:00
Ah my mistake. It's not actually a checksum issue. I just haven't dealt enough with the crew codebase. It looks like wget is is failing to properly download the files, so it errors out (with the invalid pointer error), and crew aborts. Beyond attempting to recompile wget, I'm not sure what would cause that. Unfortunately, I don't have an ARM chromebook yet (but soon will for chromebrew development!). I'll have to leave this for the more ARM experienced, but potentially it could be a filesystem is full issue?

**Comment by brucem1976** [comment] 2017-05-02 05:05
Thanks so much - here's my 'df' output in case it means anything:

Filesystem                                                   1K-blocks    Used Available Use% Mounted on
/dev/root                                                      1640868 1306724    334144  80% /
devtmpfs                                                       1951212       0   1951212   0% /dev
tmp                                                            1952476     160   1952316   1% /tmp
run                                                            1952476     472   1952004   1% /run
shmfs                                                          1952476  128972   1823504   7% /dev/shm
/dev/mmcblk0p1                                                25534700 2804012  21410548  12% /home
/dev/mmcblk0p8                                                  114928   20464     92008  19% /usr/share/oem
/dev/mapper/encstateful                                        7535880   79300   7440196   2% /var
media                                                          1952476       0   1952476   0% /media
none                                                           1952476       0   1952476   0% /sys/fs/cgroup
/home/.shadow/1ba1c7fb2fc113e121bc7b94ebbd1725091ccf40/vault  25534700 2804012  21410548  12% /home/chronos/user
tmpfs                                                          1952476       4   1952472   1% /run/arc/oem
tmpfs                                                          1952476       0   1952476   0% /run/arc/sdcard
tmpfs                                                          1952476       0   1952476   0% /run/arc/obb
tmpfs                                                          1952476       0   1952476   0% /run/arc/media
/dev/fuse                                                     25534700 2804012  21410548  12% /run/arc/sdcard/default/emulated
/dev/fuse                                                     25534700 2804012  21410548  12% /run/arc/sdcard/read/emulated
/dev/fuse                                                     25534700 2804012  21410548  12% /run/arc/sdcard/write/emulated
passthrough                                                    1952476       0   1952476   0% /run/arc/media/removable

**Comment by brucem1976** [comment] 2017-05-02 05:58
I have also check that I am able to use wget on files generally, it seems to work - strange that it would fail on both strace and python27 downloads...

**Comment by brucem1976** [comment] 2017-05-02 06:05
Ok, some progress - for some reason, if I sudo the wget of python, it works, however crew doesn't allow sudo so I'm not sure how to progress. It's not an issue with being able to write/not write to a specific directory, I checked that

**Comment by brucem1976** [comment] 2017-05-02 06:47
Ok, managed to download the python tar to the correct directory, and it got a lot further, until:

Traceback (most recent call last):
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ensurepip/__init__.py", line 205, in _main
    default_pip=args.default_pip,
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ensurepip/__init__.py", line 108, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ensurepip/__init__.py", line 31, in _run_pip
    import pip
  File "/tmp/tmpnMtOOb/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 28, in <module>
  File "/tmp/tmpnMtOOb/pip-9.0.1-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmpnMtOOb/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 36, in <module>
  File "/tmp/tmpnMtOOb/pip-9.0.1-py2.py3-none-any.whl/pip/utils/glibc.py", line 4, in <module>
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes
make: *** [install] Error 1
python27 failed to install: `make DESTDIR=/usr/local/tmp/crew/dest install` exited with 2

**Comment by lyxell** [comment] 2017-05-02 21:31
@brucem1976 @ntchambers The problem is most likely an collision between regular arm and aarch64. We've solved it by introducing --no-asm flags in other packages.

**Comment by lyxell** [comment] 2017-05-02 21:35
This was probably solved by #591

**Comment by brucem1976** [comment] 2017-05-03 06:33
Thanks, this change gets openssl compiling. However, I hit further errors:

1. some really weird wget core dump when getting python27. The chromebook has had a powerwash, so no strange settings, and it is no a folder permissions thing as wget also crashes when trying to download python to ~/Downloads. Workaround is to 'sudo wget' (which works for some reason) the python gz into /usr/local/tmp/crew

2. the above gets python compiling, but it then crashes with:
Traceback (most recent call last):
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ensurepip/__init__.py", line 205, in _main
    default_pip=args.default_pip,
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ensurepip/__init__.py", line 108, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ensurepip/__init__.py", line 31, in _run_pip
    import pip
  File "/tmp/tmpmD_XQY/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 28, in <module>
  File "/tmp/tmpmD_XQY/pip-9.0.1-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmpmD_XQY/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 36, in <module>
  File "/tmp/tmpmD_XQY/pip-9.0.1-py2.py3-none-any.whl/pip/utils/glibc.py", line 4, in <module>
  File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes
make: *** [install] Error 1
python27 failed to install: `make DESTDIR=/usr/local/tmp/crew/dest install` exited with 2

**Comment by ksunden** [comment] 2017-05-22 22:39
I was able to install without the openssl dependency (just remove the line)

**Comment by ntchambers** [comment] 2017-05-22 22:40
This is true, however it is generally nice to have openSSL support in python.

**Comment by brucem1976** [comment] 2017-05-23 09:19
Sorry for the silly question - what file do I need to remove the line from?

**Comment by ksunden** [comment] 2017-05-23 14:46
@brucem1976 python27.rb (the line is "depends_on 'openssl'"

@ntchambers I agree, however, installing openssl on aarch64 machines seems to break quite a lot at the moment. The only way I've been able to get it to install is with 'no-asm', and then it causes problems ranging from ssh to wget. Perhaps there is a different set of installation options that does not cause these problems.

**Comment by lyxell** [comment] 2017-05-23 14:50
I think the best solution is to await an aarch64-native compiler

**Comment by jam7** [comment] 2017-05-24 10:52
@lyxell It looks like aarch64 user land is not compiled by native compiler.  It seems to be compiled by armv7l compiler.  It is the reason why I close #617.

The best way to do is build openssl by hand and perform `make check` on aarch64 to figure out the real source of problem.  If I own a aarch64 machine, I could do that...  I'm waiting for c101pa.  :)

**Comment by lyxell** [comment] 2017-05-30 16:44
@jam7 Yeah, looks like you're right, the kernel ABI is aarch64 but user ABI is arm as per https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices

However, armv7-a and armv8-a are not fully compatible, e.g. SWP instruction is not available for armv8-a.

**Comment by brucem1976** [comment] 2017-05-31 06:41
Thanks for tip on excluding openssl - now I get:

zipimport.ZipImportError: can't decompress data; zlib not available

Any way to install this zlib on an arm-based system?

**Comment by lyxell** [comment] 2017-05-31 07:03
@brucem1976 `crew install zlibpkg`

**Comment by brucem1976** [comment] 2017-05-31 14:57
Thanks lyxell - so after installing that, it failed further on:

`File "/usr/local/tmp/crew/Python-2.7.13.tar.xz.dir/Python-2.7.13/Lib/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes
make: *** [install] Error 1`

**Comment by jam7** [comment] 2017-06-03 02:55
@lyxell and others who use aarch64, I made a new toolchains for armv7l without cortex-a15 optimizations.  If you can, please try it and let us know the result.  Usage is:
```
$ cd /usr/local/lib/crew
$ git remote add jam7 https://github.com/jam7/chromebrew.git
$ git fetch jam7
$ git co jam7/aarch64
$ crew upgrade
```
Then, compile `openssl` by:
```
$ crew remove openssl
$ crew install openssl
```
They try `wget` or `curl` to see whether this new toolchains could compile openssl correctly or not.

**Comment by jam7** [comment] 2017-06-05 22:11
Ok.  Above new toolchains without cortex-a15 optimizations doesn't help, mentioned by https://github.com/skycocker/chromebrew/issues/665#issuecomment-306317223.

**Comment by thedamian** [comment] 2017-06-12 18:18
issue seems to be the same as https://github.com/skycocker/chromebrew/issues/665#issuecomment-306317223

closing this issue

**Closed by thedamian** 2017-06-12 18:18 UTC
Labels: aarch64
