### ISSUE TITLE
unzip has a build dependency on wget

### ISSUE THREAD

**Issue by perryh2** [skycocker/chromebrew#3208] opened 2019-03-03 08:38 UTC
## Description
When attempting to install unzip from source as the first dependency of buildessential, it turns out that wget is needed to retrieve the patches.

```shell
unzip failed to install: `wget --continue --no-check-certificate https://launchpad.net/ubuntu/+archive/primary/+files/unzip_6.0-20ubuntu1.debian.tar.xz -O unzippatches.tar.xz` exited with 127
```

wget has not been installed yet because it is farther down the buidessential dependency list.

## Versions and system information
chromebrew: 1.2.1

ChromeOS:
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BB86912A-29BE-A59B-31EF-8F4DD1C023E2}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BB86912A-29BE-A59B-31EF-8F4DD1C023E2}
CHROMEOS_RELEASE_BOARD=enguarde-signed-mp-v25keys
CHROMEOS_RELEASE_BRANCH_NUMBER=113
CHROMEOS_RELEASE_BUILDER_PATH=enguarde-release/R71-11151.113.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.113.0 (Official Build) stable-channel enguarde
CHROMEOS_RELEASE_KEYSET=mp-v25
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.113.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.113.0

Model: Lenovo N21 Chromebook

Architecture: x86_64

**Comment by JL2210** [comment] 2019-03-03 13:21
You need to install buildessential from binaries first, before you install
any other packages.

**Comment by perryh2** [comment] 2019-03-04 08:16
... and the first thing "crew install buildessential" does is to install unzip.

**Comment by JL2210** [comment] 2019-03-04 12:26
That's because you have CREW_PREFIX set. We're still working that all out.
For now, can you close this, as it won't affect (or bother) most users?

**Comment by JL2210** [comment] 2019-03-25 16:35
Not a bug, see my comment on #3209

**Closed** 2019-06-23 03:37 UTC
Labels: bug, x86_64
