### ISSUE TITLE
Error when installing libsigsegv: libmpc.so.2 not found

### ISSUE THREAD

**Issue by aghasemi** [skycocker/chromebrew#234] opened 2016-11-06 21:23 UTC
Hi,
when installing libsigsegv which is a depedency for nano, I got this

```
/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/cc1: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
```

which makes `./configure` fail. The file is already in `/usr/local/lib` though...

I tried older sigsegv version as well.

**Comment by lyxell** [comment] 2016-12-13 22:55
Duplicate of #103

**Closed by lyxell** 2016-12-13 22:55 UTC
