### ISSUE TITLE
pip: ERROR: XMLRPC request failed

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5291] opened 2021-02-27 08:33 UTC
```
$ pip search python
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.
```

**Comment by satmandu** [comment] 2021-02-28 01:36
Not a bug:

https://stackoverflow.com/a/65365449

**Comment by uberhacker** [comment] 2021-02-28 01:49
Until they actually resolve the problem by opening up their network or providing an alternative solution, I will still consider it an issue.

**Comment by satmandu** [comment] 2021-02-28 02:03
Does ```pip install pip-search``` help at all?  It's for sure an issue for people who use the functionality, but insofar as upstream is literally deprecating the functionality by disabling the server-side API, I don't think this is going to be a problem we should try to or can address meaningfully on our end.

**Comment by uberhacker** [comment] 2021-02-28 09:26
Unfortunately, no:
```
$ pip_search python
Traceback (most recent call last):
  File "/usr/local/lib64/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib64/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib64/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib64/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib64/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib64/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib64/python3.9/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib64/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib64/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib64/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip_search", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pip_search/pip_search.py", line 16, in main
    search()
  File "/usr/local/lib/python3.9/site-packages/pip_search/pip_search.py", line 21, in search
    f = request.urlopen('https://pypi.org/search/?q=%s' % keyword)
  File "/usr/local/lib64/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib64/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/lib64/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib64/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib64/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
```

**Comment by saltedcoffii** [comment] 2022-03-19 00:12
Closing at notabug

**Closed by saltedcoffii** 2022-03-19 00:12 UTC
Labels: wontfix, aarch64, x86_64, arm, i686
