### ISSUE TITLE
Go build fails in test phase

### ISSUE THREAD

**Issue by akalin** [skycocker/chromebrew#87] opened 2015-07-12 11:55 UTC
I get this:

```
# Testing packages.
fork/exec /tmp/go-build214772872/cmd/addr2line/_test/addr2line.test: permission denied
FAIL    cmd/addr2line   0.001s
?       cmd/cgo [no test files]
fork/exec /tmp/go-build214772872/cmd/fix/_test/fix.test: permission denied
FAIL    cmd/fix 0.001s
fork/exec /tmp/go-build214772872/cmd/go/_test/go.test: permission denied
FAIL    cmd/go  0.001s
fork/exec /tmp/go-build214772872/cmd/gofmt/_test/gofmt.test: permission denied
FAIL    cmd/gofmt       0.001s
fork/exec /tmp/go-build214772872/cmd/nm/_test/nm.test: permission denied
...
```

**Comment by akalin** [comment] 2015-07-19 03:15
Ah, this is probably because /tmp (and a bunch of other partitions) are mounted as noexec.

**Comment by akalin** [comment] 2015-07-19 03:21
Ugh, also one of the tests tries to mkdir from /, which fails because it's mounted as read-only.

**Comment by lagerratrobe** [comment] 2015-07-30 23:06
Confirmed.  I can get past the /tmp problem by remounting it, but the attempt to write at / is still a problem.
```--- FAIL: TestMkdirAllAtSlash (0.00s)
        path_test.go:217: MkdirAll "/_go_os_test/dir": mkdir /_go_os_test: read-only file system```
Since this is in the go tests, not sure how to address this.

**Comment by yoki123** [comment] 2015-12-26 09:47
I download binary golang package from office website, just look at https://github.com/golang/go/wiki/ChromeOS#install-go

**Comment by lyxell** [comment] 2016-12-14 17:26
Resolved in #265

**Closed by lyxell** 2016-12-14 17:26 UTC
