### ISSUE TITLE
Can't Install Node Stable

### ISSUE THREAD

**Issue by bannostookaylo** [skycocker/chromebrew#143] opened 2016-02-04 05:10 UTC
I get these errors when trying to run 
`sudo crew install node_stable`

```
Building from source, this may take a while...
/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/cc1plus: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
WARNING: C++ compiler too old, need g++ 4.8 or clang++ 3.4 (CXX=g++)
/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/cc1: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
WARNING: C compiler too old, need gcc 4.2 or clang 3.2 (CC=gcc)
creating  ./icu_config.gypi

```

```
WARNING: warnings were emitted in the configure phase
make -C out BUILDTYPE=Release V=1
make[1]: Entering directory `/usr/local/tmp/crew/node-v5.4.1/out'
  g++  -I../deps/gtest -I../deps/gtest/include  -pthread -Wall -Wextra -Wno-unused-parameter -m32 -Wno-missing-field-initializers -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /usr/local/tmp/crew/node-v5.4.1/out/Release/.deps//usr/local/tmp/crew/node-v5.4.1/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o.d.raw   -c -o /usr/local/tmp/crew/node-v5.4.1/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o ../deps/gtest/src/gtest-death-test.cc
/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/cc1plus: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
make[1]: *** [/usr/local/tmp/crew/node-v5.4.1/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o] Error 1
make[1]: Leaving directory `/usr/local/tmp/crew/node-v5.4.1/out'
make: *** [node] Error 2
node_stable failed to install: `make` exited with 2
```

**Comment by skycocker** [comment] 2016-02-04 11:38
@bannostookaylo you cannot use `crew` with sudo - this is likely the cause of any issues. Remove all your chromebrew-installed packages (if any), then remove chromebrew itself, reinstall chromebrew as non-root user, and then try to install everything you need without sudo. If the problem persists - let us know then. If you need any help with this - don't hestitate to ask as well.

**Comment by bannostookaylo** [comment] 2016-02-06 02:24
@skycocker  I did as you said and removed it and re-installed without sudo ... now when I run it I get this

`Build Tools:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether /usr/local/bin/make: sets $(MAKE)... no
checking for gcc... gcc -m64
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
libsigsegv failed to install: `./configure --libdir=/usr/local/lib64/ CC="gcc -m64" CFLAGS=" -fPIC"` exited with 77`

**Comment by ealgase** [comment] 2016-02-08 12:00
Happens to me, too.

**Comment by thedamian** [comment] 2016-02-08 15:45
can you guys look at the config.log like we asked? 

I think it might be in the /usr/local/tmp/crew/**Package name** (try "buildtools" or somethign like that, what ever is newest)

**Comment by bannostookaylo** [comment] 2016-02-10 04:24
I can't seem to find the config.log file

**Comment by bannostookaylo** [comment] 2016-02-11 05:14
looks like this is an error  i get trying to install anything

**Comment by thedamian** [comment] 2016-02-11 05:18
So just to be clear. You are getting an error installing any package? If so please create a new issue. It is most likely just you. You should start from the beginning. But it won't help to put the details in this issue.

**Comment by bannostookaylo** [comment] 2016-02-11 05:25
nevermind... i got this error trying to install tmux however i was just able to install openssl without any issues

**Comment by thedamian** [comment] 2016-02-11 16:14
@bannostookaylo can you try running each of the following lines ONE AT A TIME and then after EACH line do a crew install tmux

1) ln -s /usr/local/bin/gcc /usr/local/bin/cc
THEN RUN "crew install node_stable"
didn't work?
2) ln -s /usr/local/lib64/libmpc.so.3 /usr/local/lib64/libmpc.so.2
then run "crew install node_stable"

- Worked? POST THAT IT WORKED AND WHAT WORKED HERE PLEASE.
- DIDN'T WORK? 
copy and paste your WHOLE output here pleease.

**Comment by bannostookaylo** [comment] 2016-02-12 05:34
@thedamian Sorry it did not work... 

```
chronos@localhost / $ crew install node_stable
/usr/local/bin/crew:18: warning: Insecure world writable dir /usr/local in PATH, mode 040777
Found node_stable, version 5.4.1
Following packages also need to be installed: 
libsigsegv diffutils bz2 ncurses binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential python27 
Do you agree? [Y/n]
Y
Proceeding...
Found libsigsegv, version 2.10
No precompiled binary available for your platform, downloading source...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2016-02-11 23:33:36--  ftp://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.10.tar.gz
           => 'libsigsegv-2.10.tar.gz'
Resolving ftp.gnu.org... 208.118.235.20
Connecting to ftp.gnu.org|208.118.235.20|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /gnu/libsigsegv ... done.
==> SIZE libsigsegv-2.10.tar.gz ... 402279
==> PASV ... done.    ==> RETR libsigsegv-2.10.tar.gz ... done.
Length: 402279 (393K) (unauthoritative)

libsigsegv-2.10.tar.gz    100%[=======================================>] 392.85K  1.32MB/s   in 0.3s   

2016-02-11 23:33:36 (1.32 MB/s) - 'libsigsegv-2.10.tar.gz' saved [402279]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...

Build Tools:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether /usr/local/bin/make: sets $(MAKE)... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
libsigsegv failed to install: `./configure --libdir=/usr/local/lib64/ CC="gcc" CFLAGS=" -fPIC"` exited with 77
```

**Comment by bannostookaylo** [comment] 2016-02-12 06:12
So i made my system writable and read the config.log files from trying to compile and install Python 2.7 ... anyway doing the fixes for that now lets me get further in the crew install process.

```

sudo ln -s /usr/local/lib64/libmpc.so.3 /usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/libmpc.so.2
sudo ln -s /usr/local/lib/libc_nonshared.a /usr/lib64/libc_nonshared.a
```

now i am down to this error
```

/usr/local/bin/make: TARGETSTACK=" all" all-recursive
/bin/bash: /usr/local/bin/make:: No such file or directory
make: *** [all] Error 127
libsigsegv failed to install: `make` exited with 2
```

**Comment by faddah** [comment] 2016-04-14 01:53
+1 - i get another error, but i can't get either the 'node' or 'node_stable" packages to build all the way through, i get an error similar to @bannostookaylo first post. @skycocker - can anything be done about this please? 

best,

‒  faddah
    portland, oregon, u.s.a.

**Comment by thedamian** [comment] 2016-05-27 14:48
Fixed in pull https://github.com/skycocker/chromebrew/pull/173

**Comment by samuelwight** [comment] 2016-07-16 15:22
I had to do a reinstall of chromebrew and tried to install node and I'm getting the same error.

```
/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/cc1plus: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
make[1]: *** [/usr/local/tmp/crew/node-v4.4.5/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o] Error 1
make[1]: Leaving directory `/usr/local/tmp/crew/node-v4.4.5/out'
make: *** [node] Error 2
node failed to install: `make` exited with 2
```

**Comment by lyxell** [comment] 2016-12-13 22:56
Duplicate of #103

**Closed by lyxell** 2016-12-13 22:56 UTC
